language: c
sudo: false
env:
  global:
      secure: "SGTth3HNpEzXRqD28M5AcY6Q89irS3Ituw1t0gQFIurhsoRQnmKRTVwtv8lc6oAprQtxrJAYgf4RJ10k7zEuP5I516G4TMTpS63JHhUdagcVn86CaI3/XO6RlX8YSVrJXVJhUVxITSDUxY7BU3YMP1zfiEE1LODgH/jac9Bumlr4KeWtFRHFI90gUJ1dJWgm7skQ83ZpquZSd+xfWOtCUCZRvMIyRflaTmmfYFET2Q3xHUFlRUMMdINSuDH1pA1pUO6xav2MQI3b0Ea6X0NR2sGplbTCDNpn3lOYCO+H2DMP4w3ZUGkDNbn2wdffGESIgslQKED9ZJ+TbUUbBIiKBiMqCH1j1aWQcwzSMZRvq4eviK/iqmC30z57nI7sOPu30zhezJjobtTCVzYXOsVSoYsAH0f555L5Vk1gGjqWsLI/7clbN0DJDSX2cWNmKoYP86eJmr0KyzDhpygquLZIPvdIMIOai3N4o09PwNfkOscO+fePHRXuKXte2CuVQASu40y4K1Boylem6kTupvfvPFqKfIKgHWIsRWoj+XVeTIRVUYj2WerYpKd/egSzsi99FmcEPY1Tne/6JkWMgvp5YgljHmBuw8SFBUirNb3fwG3VrclFuJ2z3zKXcs5SLsKpW+r6/9YwZBdaYey5r2uOZjs7GDIIYg77jKunVAbhTrM="
matrix:
  include:
  # full testsuite
  - os: linux
    compiler: gcc
    env: OOT=0 TEST=1 THR="none" CONF="auto"
  # test x86_64 ukrs with SDE
  - os: linux
    compiler: gcc
    env: OOT=0 TEST=0 SDE=1 THR="none" CONF="x86_64"
  # openmp build
  - os: linux
    compiler: gcc
    env: OOT=0 TEST=0 SDE=0 THR="openmp" CONF="auto"
  # pthreads build
  - os: linux
    compiler: gcc
    env: OOT=0 TEST=0 SDE=0 THR="pthreads" CONF="auto"
  # out-of-tree build
  - os: linux
    compiler: clang
    env: OOT=1 TEST=0 SDE=0 THR="none" CONF="auto"
  # clang build
  - os: linux
    compiler: clang
    env: OOT=0 TEST=0 SDE=0 THR="none" CONF="auto"
  # macOS with system compiler (clang)
  - os: osx
    compiler: clang
    env: OOT=0 TEST=0 SDE=0 THR="none" CONF="auto"
install:
- if [ "$CC" = "gcc" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - clang
script:
- export DIST_PATH=.
- pwd
- if [ $OOT -eq 1 ]; then mkdir oot; cd oot; export DIST_PATH=..; fi
- pwd
- $DIST_PATH/configure -t $THR CC=$CC $CONF
- pwd
- ls -l
- $CC --version
- make -j 2
- if [ $TEST -eq 1 ]; then $DIST_PATH/travis/do_testsuite.sh; fi
- if [ $SDE -eq 1 ]; then $DIST_PATH/travis/do_sde.sh; fi
